const STATUS_BAD_REQUEST = 400;
const STATUS_BAD_AUTH = 401;
const STATUS_FORBIDDEN = 403;
const STATUS_NOT_FOUND = 404;
const STATUS_EMAIL_DUBLICATE = 409;
const STATUS_SERVER_ERR = 500;

module.exports = {
  STATUS_BAD_REQUEST,
  STATUS_BAD_AUTH,
  STATUS_FORBIDDEN,
  STATUS_NOT_FOUND,
  STATUS_EMAIL_DUBLICATE,
  STATUS_SERVER_ERR,
};
